Add our own copy.exe binary so that we can copy without cmd.exe
01org/intel-arduino-tools pull request #65
Opened 2016-10-24 21:39 UTC by calvinatintel

in response to https://github.com/01org/corelibs-arduino101/issues/309

2016-10-24 22:36 UTC, eriknyquist requested changes

2016-10-24 22:36 UTC, eriknyquist commented on arduino101load/arduino101copy.go
> +        log.Fatal("copy.exe <source> <destination>")
use `os.Args[0]` instead of hardcoding `copy.exe`

2016-10-24 22:37 UTC, eriknyquist commented on arduino101load/arduino101copy.go
> +        log.Fatal("ERROR:", err)
Any particular reason for using log.* functions for errors, instead of just `fmt.Printf`?

2016-10-24 22:39 UTC, calvinatintel commented on arduino101load/arduino101copy.go
> +        log.Fatal("copy.exe <source> <destination>")
Good call. It's not even called `copy.exe` anymore.

2016-10-24 22:42 UTC, calvinatintel commented on arduino101load/arduino101copy.go
> +        log.Fatal("ERROR:", err)
`log.Fatal` is `fmt.Print` followed by `os.Exit(1)`
https://golang.org/pkg/log/#Fatal

2016-10-24 22:47 UTC, eriknyquist requested changes

2016-10-24 22:47 UTC, eriknyquist commented on arduino101load/arduino101copy.go
> +    destination_file, err := os.Create(destination_path)
Looks like you're creating an empty version of the dest. file in order to check if you can access that path? is there a cleaner way to do that?

2016-10-24 22:50 UTC, calvinatintel commented on arduino101load/arduino101copy.go
> +    destination_file, err := os.Create(destination_path)
It creates to get a file handle, so that `io.Copy()` can use it

2016-10-24 23:00 UTC, eriknyquist commented on arduino101load/arduino101copy.go
> +    destination_file, err := os.Create(destination_path)
OK, fair enough

2016-10-24 23:01 UTC, eriknyquist approved these changes

2016-10-25 00:14 UTC, calvinatintel commented
@facchinm and everyone, please test.

1. Install vanilla 1.0.7
2. Replace the content of `Arduino15\packages\Intel\tools\arduino101load\1.6.9+1.28` with [this](https://github.com/calvinatintel/intel-arduino-tools/archive/windows.zip)
3. Replace `Arduino15\packages\Intel\hardware\arc32\1.0.7\platform.txt` with [this](https://raw.githubusercontent.com/calvinatintel/corelibs-arduino101/master/platform.txt)
4. Turn on verbose mode on compilation
5. Compile

At the end of the compilation, you should see this.
```
Linking everything together...
"C:\Users\scpark\AppData\Local\Arduino15\packages\Intel\tools\arc-elf32\1.6.9+1.0.1/bin/arc-elf32-gcc" -nostartfiles -nodefaultlibs -nostdlib -static -Wl,-X -Wl,-N -Wl,-mcpu=quarkse_em -Wl,-marcelf -Wl,--gc-sections "-TC:\Users\scpark\AppData\Local\Arduino15\packages\Intel\hardware\arc32\1.0.7\variants\arduino_101/linker_scripts/flash.ld" "-Wl,-Map,C:\Users\scpark\AppData\Local\Temp\arduino_build_129492/Blink.ino.map"  -o "C:\Users\scpark\AppData\Local\Temp\arduino_build_129492/Blink.ino.elf" "-LC:\Users\scpark\AppData\Local\Temp\arduino_build_129492" "-LC:\Users\scpark\AppData\Local\Arduino15\packages\Intel\hardware\arc32\1.0.7\variants\arduino_101" -Wl,--whole-archive "-larc32drv_arduino101" -Wl,--no-whole-archive -Wl,--start-group "-larc32drv_arduino101" -lnsim -lc -lm -lgcc "C:\Users\scpark\AppData\Local\Temp\arduino_build_129492\sketch\Blink.ino.cpp.o" "C:\Users\scpark\AppData\Local\Temp\arduino_build_129492\core\variant.cpp.o" "C:\Users\scpark\AppData\Local\Temp\arduino_build_129492/core\core.a"
C:\Users\scpark\AppData\Local\Arduino15\packages\Intel\tools\arduino101load\1.6.9+1.28/arduino101load/arduino101copy.exe "C:\Users\scpark\AppData\Local\Temp\arduino_build_129492\Blink.ino.elf" "C:\Users\scpark\AppData\Local\Temp\arduino_build_129492\..\arduino101_sketch.debug.elf"
2016/10/24 17:09:34 C:\Users\scpark\AppData\Local\Temp\arduino_build_129492\Blink.ino.elf copied to C:\Users\scpark\AppData\Local\Temp\arduino_build_129492\..\arduino101_sketch.debug.elf
"C:\Users\scpark\AppData\Local\Arduino15\packages\Intel\tools\arc-elf32\1.6.9+1.0.1/bin/arc-elf32-objcopy" -S -O binary -R .note -R .comment -R COMMON -R .eh_frame  "C:\Users\scpark\AppData\Local\Temp\arduino_build_129492/Blink.ino.elf" "C:\Users\scpark\AppData\Local\Temp\arduino_build_129492/Blink.ino.bin"
"C:\Users\scpark\AppData\Local\Arduino15\packages\Intel\tools\arc-elf32\1.6.9+1.0.1/bin/arc-elf32-strip" "C:\Users\scpark\AppData\Local\Temp\arduino_build_129492/Blink.ino.elf"
"C:\Users\scpark\AppData\Local\Arduino15\packages\Intel\tools\arc-elf32\1.6.9+1.0.1/bin/arc-elf32-objcopy" -S -O ihex -R .note -R .comment -R COMMON -R .eh_frame  "C:\Users\scpark\AppData\Local\Temp\arduino_build_129492/Blink.ino.elf" "C:\Users\scpark\AppData\Local\Temp\arduino_build_129492/Blink.ino.hex"
```
The line that starts with the date shows that the copy was successful.

2016-10-25 07:58 UTC, facchinm commented
It works perfectly! Only a couple of suggestions:
* use `fmt` instead than `log` to avoid printing the date
* accept a `verbose` flag to avoid printing anything if verbose is not set
* we can avoid shipping the additional binary if we call `arduino101load` with a `copy` flag

Anyway, that's perfectly fine to leave it as is :smile:

2016-10-25 16:45 UTC, calvinatintel commented
Thanks @facchinm I'll make those changes. I would prefer to keep `arduino101load` separate from `arduino101copy` if you're okay with that.

2016-10-25 16:46 UTC, eriknyquist commented
@calvinatintel I haven't tested yet, but let me know when you make those changes and I'll test after

2016-10-25 21:04 UTC, calvinatintel commented
`log.Printf()` was printing to `stderr` for some reason which ignored the verbose flag. I've replaced it with `fmt.Printf()` and now it respects the verbose flag on the settings. I've left the others to `log.Fatal()` since those are actually error conditions.

@facchinm What do you think?
@eriknyquist Please test

2016-10-26 22:23 UTC, eriknyquist approved these changes
Tested on Windows 7, works well.

2016-10-27 22:57 UTC, merged